# Generated by Django 5.0.6 on 2024-06-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image_url',
            field=models.URLField(default='https://images.wikidexcdn.net/mwuploads/wikidex/4/4f/latest/20230130122413/Pok%C3%A9_Ball_HOME.png'),
        ),
    ]
