# Generated by Django 5.0.6 on 2024-06-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_pokemon_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='image_url',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(null=True, upload_to='pokemon_images'),
        ),
    ]
