# Generated by Django 5.0.6 on 2024-06-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_pokemon_image_url_pokemon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(default='pokemon_images/default.png', upload_to='pokemon_images/'),
        ),
    ]
