# Generated by Django 5.0.6 on 2024-06-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_pokemon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='image',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='image_url',
            field=models.URLField(default='https://images.wikidexcdn.net/mwuploads/wikidex/4/4f/latest/20230130122413/Pok%C3%A9_Ball_HOME.png'),
        ),
    ]
