# Generated by Django 5.0.6 on 2024-07-03 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_pokemon_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='description',
        ),
    ]
